### ISSUE TITLE
Dead zone ?

### ISSUE THREAD

**Issue by Wronschien** [samuelgr/Xidi#30]
Hello, is it possible to define a dead zone for an axis ?
I couldn't find any setting about that.
Thank you.

**Comment by samuelgr** [comment]
There isn't a setting available directly via Xidi.

Deadzone is a property that applications can change via DirectInput, and Xidi will honor whatever the application requests. Some applications expose it as a setting that users can configure.

**Comment by Wronschien** [comment]
Well I was afraid so. My problem is with the game Omikron which doesn't provide this setting. It is much too sensitive to the axis movement, it behaves quite erratically even in the menus. I think I will simply bind the left stick to the keyboard arrows, this should hide it from the game.

Thanks for your reply.

**Comment by v00d00m4n** [comment]
Most of old games does not provide deadzone setting, they rely on DirectInput deadzone calibration made with joy.cpl, but unfortunately since Windows Xp or Vista directinput deadzone settings was completely broken or removed and there are some games that does not have even hardcoded deadzone, like for example Need for Speed most wanted (one i clearly remember that had my cars steering to left because of lack of deadzone), and most of games had no internal measures to set it, so the only way to set deadzone is to do it via wrapper, such XIDI, its really a must have feature.

**Comment by Wronschien** [comment]
That's an idea xinputplus, I knew about it but didn't think of using it alongside xidi. It may work but for now I stored the game away and don't know when I'll actually play it. But I should try that next time the problem occurs, thanks !

**Comment by samuelgr** [comment]
The other thing is that WinMM doesn't provide a way of configuring deadzone. I think the right answer here is to make it configurable via the Xidi configuration file.

**Comment by samuelgr** [comment]
Implemented in 0d53fec78259065703cd466f417656c39f4eb0ac.
