### ISSUE TITLE
buttons work but unable to configure D-pad

### ISSUE THREAD

**Issue by CorpseSlayer** [samuelgr/Xidi#64]
As an emulator fan the very first thing i had to try when heard about this was  i need to try  this on my favorite emulator WinKawaks
i stop using it a long time ago cause they never added X-input to the emulator , the problem i am having is when trying to configure
my Xbox controller buttons in a miracle way i was able to configure them but sadly i could only configure the L Stick but not the D-pad
as you may know old games/emulator are more playable using the D-pad instead of  the L-Stick is there a way to make that XIDI work to configure the D-pad too?

**Comment by samuelgr** [comment]
Are you using a configuration file (`Xidi.ini`) to tell Xidi to map the d-pad the way you want?

[Here](https://github.com/samuelgr/XidiGameConfigurations/blob/master/GameConfigurations/Snes9x/Xidi.ini) is an example, for Snes9x, that sets up the d-pad so it does the same thing as the left stick.

I think this is just a matter of getting Xidi configured correctly. Please re-open if you believe this is actually a bug in Xidi, rather than a configuration issue, or if you need more help getting Xidi configured then feel free to start a Q&A (see the [Discussions](https://github.com/samuelgr/Xidi/discussions) tab).

**Comment by CorpseSlayer** [comment]
ok thanks i will try it..
